"""add git_revision to evaluations

Revision ID: d7c4d17bcbd9
Revises: 0fcf18faa464
Create Date: 2025-11-30 14:55:20.049603+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd7c4d17bcbd9'
down_revision: Union[str, Sequence[str], None] = '0fcf18faa464'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attestations', schema=None) as batch_op:
        batch_op.alter_column('output_digest',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('output_name',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # Delete existing evaluations (they don't have git_revision)
    # Must delete evaluation_output_paths first due to foreign key
    op.execute('DELETE FROM evaluation_output_paths')
    op.execute('DELETE FROM evaluations')

    with op.batch_alter_table('evaluations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('git_revision', sa.String(), nullable=False))
        batch_op.create_index(op.f('ix_evaluations_git_revision'), ['git_revision'], unique=False)
        batch_op.create_unique_constraint('uq_evaluation_jobset_revision', ['jobset_id', 'git_revision'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('evaluations', schema=None) as batch_op:
        batch_op.drop_constraint('uq_evaluation_jobset_revision', type_='unique')
        batch_op.drop_index(op.f('ix_evaluations_git_revision'))
        batch_op.drop_column('git_revision')
    with op.batch_alter_table('attestations', schema=None) as batch_op:
        batch_op.alter_column('output_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('output_digest',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
