"""Initial schema with all tables

Revision ID: ebd80c41f648
Revises: 
Create Date: 2025-11-12 10:00:59.598450+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ebd80c41f648'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('derivations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('drv_hash', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_derivations_drv_hash'), 'derivations', ['drv_hash'], unique=False)
    op.create_table('link_patterns',
    sa.Column('pattern', sa.String(), nullable=False),
    sa.Column('link', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('pattern')
    )
    op.create_table('reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('definition', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('attestations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('output_digest', sa.String(), nullable=False),
    sa.Column('output_name', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('drv_id', sa.Integer(), nullable=False),
    sa.Column('output_hash', sa.String(), nullable=False),
    sa.Column('output_sig', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['drv_id'], ['derivations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.Column('valid', sa.Boolean(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tokens')
    op.drop_table('attestations')
    op.drop_table('users')
    op.drop_table('reports')
    op.drop_table('link_patterns')
    op.drop_index(op.f('ix_derivations_drv_hash'), table_name='derivations')
    op.drop_table('derivations')
    # ### end Alembic commands ###
