"""Add jobsets and evaluations

Revision ID: 3fe755434ebe
Revises: ebd80c41f648
Create Date: 2025-11-12 13:20:04.853554+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3fe755434ebe'
down_revision: Union[str, Sequence[str], None] = 'ebd80c41f648'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jobsets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('flakeref', sa.String(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jobsets_name'), 'jobsets', ['name'], unique=True)
    op.create_table('evaluations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jobset_id', sa.Integer(), nullable=False),
    sa.Column('evaluation_number', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('derivation_count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['jobset_id'], ['jobsets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evaluations_jobset_id'), 'evaluations', ['jobset_id'], unique=False)
    op.create_table('evaluation_derivations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('evaluation_id', sa.Integer(), nullable=False),
    sa.Column('derivation_id', sa.Integer(), nullable=False),
    sa.Column('attribute_path', sa.String(), nullable=True),
    sa.Column('output_paths', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['derivation_id'], ['derivations.id'], ),
    sa.ForeignKeyConstraint(['evaluation_id'], ['evaluations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evaluation_derivations_derivation_id'), 'evaluation_derivations', ['derivation_id'], unique=False)
    op.create_index(op.f('ix_evaluation_derivations_evaluation_id'), 'evaluation_derivations', ['evaluation_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_evaluation_derivations_evaluation_id'), table_name='evaluation_derivations')
    op.drop_index(op.f('ix_evaluation_derivations_derivation_id'), table_name='evaluation_derivations')
    op.drop_table('evaluation_derivations')
    op.drop_index(op.f('ix_evaluations_jobset_id'), table_name='evaluations')
    op.drop_table('evaluations')
    op.drop_index(op.f('ix_jobsets_name'), table_name='jobsets')
    op.drop_table('jobsets')
    # ### end Alembic commands ###
